dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD
  - VERSION=3.4.0
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=2.0.0

addons:
  chrome: stable

before_install:
  # Tweak PHP configuration.
  - phpenv config-add ./tests/travis.php.ini
  - phpenv rehash

  - composer self-update
  - composer --version
  - google-chrome-stable --version

  - ORCA=$TRAVIS_BUILD_DIR/../orca
  - ORCA_FIXTURE=$ORCA-build
  - ORCA_SUT=drupal/lightning_core

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

install:
  # Clone ORCA so it can build the code base.
  - git clone --depth 1 git@github.com:acquia/orca.git ../orca
  - $ORCA/bin/travis/install

  # Use ORCA to build the code base.
  - orca fixture:init -f --sut $ORCA_SUT --sut-only

before_script:
  - cd $ORCA_FIXTURE/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION

script:
  - orca tests:run --sut-only --sut $ORCA_SUT

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended
