core.entity_view_mode.*.*.third_party.lightning_core:
  type: mapping
  label: 'Lightning'
  mapping:
    description:
      type: string
      label: 'Description'
    internal:
      type: boolean
      label: 'Internal'

user.role.*.third_party.lightning_core:
  type: mapping
  label: 'Lightning'
  mapping:
    description:
      type: string
      label: 'Description'

lightning.versions:
  type: sequence
  label: 'Lightning component versions'
  sequence:
    type: string
    label: 'Version'
